# EXERCICI 1

### partir el conjunt de dades adjunt en train/test. 
### estudiar, descriptivament,  els dos conjunts per separat.

In [1]:
import sklearn
print('The scikit-learn version is {}.'.format(sklearn.__version__))

The scikit-learn version is 1.0.2.


In [4]:
import numpy as np
import pandas as pd

# descarrega del dataset
hs = pd.read_csv('housing data.csv')
hs.head() # resum 5 primeres files

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [52]:
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split

# creació dataset (mostra de 100 valors)
X, y = make_blobs(n_samples=100)

# split en train/test
# test_size especifica el percentatge del conjunt utilitzat per fer la prova
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)


# s'ha de proporcionar o train_size o test_size
# si no es proporciona cap, per defecte s'utilitza test_size=0.25 (25% del conjunt)
# percentatges comuns (80%-20% / 67%-33% / 50%-50%)

# matriu bidimensional amb les entradas (80% del conjunt per entrenament)
X_train

array([[ -6.69543279,  -1.35024271],
       [ -4.79022731,  -1.76029178],
       [-10.20702196,   2.38584048],
       [ -8.85467342,   3.57294738],
       [ -4.50839609,  -3.99184153],
       [ -1.56381039,   3.472769  ],
       [ -6.25136694,  -3.04773093],
       [ -4.73053748,  -1.85659281],
       [-11.94231855,   5.02969425],
       [ -5.8750683 ,  -4.09299969],
       [ -0.67605585,   1.75302087],
       [ -1.65196274,   4.8153264 ],
       [ -0.19072344,   1.459004  ],
       [ -9.77488304,   2.7559986 ],
       [ -0.43379375,   2.70587062],
       [ -4.06997196,  -2.78127097],
       [ -9.84372226,   3.60448063],
       [ -1.72394129,   3.39450467],
       [ -0.89803061,   2.9789349 ],
       [-11.39513745,   3.23813097],
       [ -9.70009775,   3.27109076],
       [ -7.73889003,   5.05266448],
       [ -1.92224625,   2.54164441],
       [ -9.26929703,   3.00363981],
       [ -5.13450166,  -1.90284402],
       [-10.92527359,   2.73027508],
       [ -5.83016527,  -1.90954024],
 

In [53]:
# matriu bidimensional amb les entradas (20% del conjunt per prova)
X_test

array([[ -0.3290959 ,   3.71046466],
       [  0.04463694,   2.14937231],
       [ -9.54127974,   2.81082347],
       [ -4.9693762 ,  -0.67022586],
       [ -0.41869108,   3.89467039],
       [ -7.85181697,   4.90159987],
       [-10.8116534 ,   4.19526991],
       [ -8.94128661,   1.08888707],
       [ -0.67150884,   2.052029  ],
       [ -5.8588173 ,  -0.27627179],
       [ -1.8494345 ,   2.99882286],
       [ -1.12968445,   2.00429712],
       [-11.09524826,   4.59844754],
       [  0.06891874,   1.37622584],
       [ -5.94133192,  -1.86407312],
       [ -5.47532111,   0.17705269],
       [ -9.91166028,   3.76512599],
       [ -2.70319327,  -2.0205507 ],
       [ -1.2950946 ,   1.75266701],
       [ -4.70852234,   0.88308281]])

In [54]:
# matriu unidimensional amb les sortides (entrenament)
y_train

array([0, 0, 1, 1, 0, 2, 0, 0, 1, 0, 2, 2, 2, 1, 2, 0, 1, 2, 2, 1, 1, 1,
       2, 1, 0, 1, 0, 2, 1, 0, 0, 1, 2, 2, 0, 1, 0, 0, 1, 0, 1, 1, 2, 1,
       2, 1, 2, 0, 1, 0, 1, 2, 1, 2, 0, 1, 0, 0, 0, 2, 1, 0, 1, 2, 0, 2,
       1, 2, 0, 2, 0, 2, 2, 2, 0, 0, 0, 1, 1, 2])

In [55]:
# matriu unidimensional amb les sortides (prova)
y_test

array([2, 2, 1, 0, 2, 1, 1, 1, 2, 0, 2, 2, 1, 2, 0, 0, 1, 0, 2, 0])

In [82]:
# igual train/test especificant train_size (igual resultat perque s'ha especificat el 80%)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.80, random_state=4, stratify=y)

# random_state: fixe el generador de número aleatori. Cada cop que s'executa la funció dóna el mateix resultat.
# resultats diferents als anteriors ja que rendom_state=4
# divisió estratificada: stratify=y: manté (aprox) proporció de valors y a través dels conjunts entrenament-prova.

X_train

array([[ 4.77050219,  8.19043982],
       [ 4.7535131 ,  9.22119361],
       [ 8.85330723,  2.48397417],
       [ 8.81866285,  1.91574623],
       [ 4.25094542, -3.19285023],
       [ 3.72620599, -2.19951995],
       [ 6.9716886 ,  7.22880789],
       [ 5.37984074,  5.97158236],
       [ 5.80694755, -3.03860652],
       [ 5.27003064, -2.38383991],
       [ 6.16899324,  6.95619954],
       [ 6.81919638,  7.1236494 ],
       [ 6.75682618,  3.18550042],
       [11.05746402,  1.83970838],
       [ 6.58153303,  2.69352367],
       [ 9.02826867,  2.20785267],
       [ 8.50303971,  6.61310693],
       [ 3.87171408, -2.24796235],
       [ 8.648001  ,  1.90589869],
       [ 7.24291336,  2.22346418],
       [ 7.93572865,  2.16754074],
       [ 8.71645299,  1.28273449],
       [ 6.4796191 ,  6.23868968],
       [ 5.07018352,  6.97784914],
       [ 7.31668282,  7.59925423],
       [ 5.36008799, -1.71299448],
       [ 7.10376242,  6.84575439],
       [ 3.59984785,  6.49175557],
       [ 3.55370707,

In [84]:
X_test

array([[ 4.43215511, -3.42016388],
       [ 7.40735619,  6.51554798],
       [ 2.82146087, -4.03748969],
       [ 6.70863874,  3.0100313 ],
       [ 8.82764571,  2.56532794],
       [ 7.25641689,  0.92102108],
       [ 4.20927754, -2.94097952],
       [ 9.45406422,  1.57390814],
       [ 3.00729936, -2.37371223],
       [ 6.13722092,  6.52001206],
       [ 5.41152143,  5.87608417],
       [10.3863284 ,  2.88163353],
       [ 5.02616791, -2.71107333],
       [ 4.40196264,  6.31658815],
       [ 6.42386177,  7.55821226],
       [ 8.03810794,  4.2928529 ],
       [ 5.24009476,  8.28181748],
       [ 8.46080211,  1.44852141],
       [ 7.55541355,  9.39370488],
       [ 5.12580522, -3.20447254]])

In [85]:
# proporció aprox de valors y en l'entrenament (divisió estratificada: stratify=y).
y_train

array([0, 0, 1, 1, 2, 2, 0, 0, 2, 2, 0, 0, 1, 1, 1, 1, 0, 2, 1, 1, 1, 1,
       0, 0, 0, 2, 0, 0, 2, 0, 2, 0, 2, 1, 2, 2, 1, 1, 2, 0, 0, 2, 2, 2,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 2, 2, 1, 2, 2, 1, 0, 2, 2, 2, 0, 0, 0,
       0, 1, 2, 1, 0, 0, 2, 2, 1, 2, 2, 1, 0, 0])

In [73]:
# proporció aprox de valors y en la prova (divisió estratificada: stratify=y).
y_test

array([2, 0, 2, 1, 1, 1, 2, 1, 2, 0, 0, 1, 2, 0, 0, 1, 0, 1, 0, 2])

In [86]:
# shuffle=False: desactiva la barreja de dades i la divisió aleatoria.
train_test_split(y, shuffle=False)

[array([0, 0, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 1, 1, 2, 0, 1, 1, 1, 0, 0, 2,
        1, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 1, 2, 2, 2, 2, 0, 2, 0, 0, 2,
        2, 2, 1, 1, 0, 1, 1, 2, 0, 1, 2, 1, 2, 0, 2, 1, 1, 2, 1, 2, 1, 1,
        1, 2, 2, 2, 0, 1, 2, 2, 1]),
 array([0, 0, 0, 1, 2, 1, 0, 0, 0, 2, 0, 2, 1, 2, 0, 0, 2, 1, 2, 1, 2, 1,
        0, 1, 1])]

In [89]:
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split

# creació dataset 
X, y = make_blobs(n_samples=100)

# split en train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=3)

# suma 5 primeres files
X_train

array([[ 8.39500351, 10.7716237 ],
       [-6.18141888, -5.65888418],
       [ 6.11897646, -8.00365488],
       [-5.92814092, -7.0120671 ],
       [-4.45165732, -6.2832657 ],
       [-7.29320566, -4.97753451],
       [-8.10380179, -7.12074985],
       [-4.52246319, -6.23911276],
       [-8.4876115 , -5.63022521],
       [ 9.00542262, 11.10125996],
       [ 9.6623815 , 10.39632871],
       [ 4.386283  , -8.37761488],
       [11.47994582,  9.73372691],
       [ 9.09787753, 10.24662621],
       [ 9.64965182,  9.93220685],
       [ 8.83072287,  9.69418519],
       [ 4.88880383, -8.97446684],
       [ 5.37062775, -7.26487386],
       [ 4.44873948, -6.11480382],
       [-7.17479715, -6.21936862],
       [ 8.57086412,  9.20076088],
       [-8.51065875, -6.54939095],
       [ 5.2945971 , -8.16632333],
       [10.24469539, 12.12215738],
       [ 8.94072537,  8.95962025],
       [-5.4252049 , -5.78961805],
       [-6.12819077, -6.3871547 ],
       [ 8.27589575, 11.07335214],
       [ 5.27391589,

# EXERCICI 2

### aplicació processos transformació

### estandarditzar les dades numèriques, crear columnes dummies, polinomis...

In [95]:

from sklearn.preprocessing import StandardScaler

scaler = preprocessing.StandardScaler().fit(X_train)
scaler
StandardScaler()

scaler.mean_


array([ 2.7439049 , -1.81210583])

In [109]:
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler().fit(X_train)

standardized_X = scaler.transform(X_train)
standardized_X_test = scaler.transform(X_test)

# mitjana
scaler.mean_

array([ 2.7439049 , -1.81210583])

In [103]:
scaler.scale_

array([6.70535698, 8.01762767])

In [105]:

X_scaled = scaler.transform(X_train)
X_scaled

array([[ 0.84277372,  1.56950785],
       [-1.33107362, -0.4797901 ],
       [ 0.50333958, -0.77224203],
       [-1.29330114, -0.64856607],
       [-1.07310651, -0.55766619],
       [-1.49687937, -0.39480864],
       [-1.61776722, -0.66212154],
       [-1.08366611, -0.55215921],
       [-1.67500648, -0.4762156 ],
       [ 0.93380826,  1.61062179],
       [ 1.03178349,  1.52269911],
       [ 0.24493522, -0.81888425],
       [ 1.30284502,  1.44005599],
       [ 0.94759647,  1.50402744],
       [ 1.02988505,  1.46481143],
       [ 0.9077545 ,  1.43512414],
       [ 0.31987841, -0.89332672],
       [ 0.39173498, -0.68009744],
       [ 0.25424964, -0.53665475],
       [-1.47922058, -0.54969662],
       [ 0.8690006 ,  1.37358171],
       [-1.67844362, -0.59085871],
       [ 0.38039618, -0.79253088],
       [ 1.11862657,  1.73795339],
       [ 0.92415967,  1.3435054 ],
       [-1.21829603, -0.4960959 ],
       [-1.32313547, -0.57062376],
       [ 0.82501064,  1.60714098],
       [ 0.3773119 ,

In [106]:
X_scaled.mean(axis=0)

array([-1.65704929e-16,  2.31986901e-17])

In [107]:
X_scaled.std(axis=0)

array([1., 1.])

In [108]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(5)
poly.fit_transform(X)

array([[1.00000000e+00, 6.32000000e-03, 1.80000000e+01, ...,
        1.94558508e+07, 2.44117251e+05, 3.06299800e+03],
       [1.00000000e+00, 2.73100000e-02, 0.00000000e+00, ...,
        1.20282040e+08, 2.76991143e+06, 6.37868240e+04],
       [1.00000000e+00, 2.72900000e-02, 0.00000000e+00, ...,
        1.01000711e+07, 1.03615525e+05, 1.06298034e+03],
       ...,
       [1.00000000e+00, 6.07600000e-02, 0.00000000e+00, ...,
        2.82617799e+07, 4.01603524e+05, 5.70683768e+03],
       [1.00000000e+00, 1.09590000e-01, 0.00000000e+00, ...,
        4.21215280e+07, 6.93728558e+05, 1.14254951e+04],
       [1.00000000e+00, 4.74100000e-02, 0.00000000e+00, ...,
        7.70798481e+07, 1.53033309e+06, 3.03830303e+04]])

# EXERCICI 3

### resum noves columnes generades de manera estadística i gràfica.