# EXERCICI 1
## creació de dos models de regressió diferents per intentar predir el millor possible el preu de les vivendes (MEDV) de l'arxiu adjunt.

In [1]:
! pip install mysql-connector-python

In [2]:
pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.


## · model: regressió lineal múltiple

In [7]:
# scikit-learn (no són necessaris resultats detallats i es vol un enfocament coherent amb altres tècniques de regressió)

# step_1: import packages and classes, per als dos models de regressió seran iguals.

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

# descarrega del dataset
pv = pd.read_csv('housing data.csv')
pv.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [95]:
# step_2: obtenir variables que volem estudiar

# y: variable dependent (MEDV) - array unidimensional
# x: variables independents (DIS i RM) - array bidimensional

x = pv[
    ["RM", "DIS"]
]
y = pv["MEDV"]
x,y = np.array(x), np.array(y)

# columnes con vertides en matrius

In [96]:
x

array([[6.575 , 4.09  ],
       [6.421 , 4.9671],
       [7.185 , 4.9671],
       ...,
       [6.976 , 2.1675],
       [6.794 , 2.3889],
       [6.03  , 2.505 ]])

In [97]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [98]:
# step_3: crear i ajustar model

model_rlm = LinearRegression().fit(x, y)

In [99]:
# step_4: obtenir resultats

r_sq = model_rlm.score(x, y)

print(f"coeficient de determinació: {r_sq}")

print(f"intercepte: {model_rlm.intercept_}")

print(f"coeficients: {model_rlm.coef_}")


coeficient de determinació: 0.4955246476058477
intercepte: -34.63605017547333
coeficients: [8.80141183 0.48884854]


In [100]:
# step_5: predir la resposta

pred = model_rlm.predict(x)
print(f"predicció resposta:\n{pred}")

predicció resposta:
[25.23262311 24.30597474 31.03025338 29.9197274  31.23113776 24.92052548
 20.99628003 22.59515685 17.89792552 21.43016488 24.59312806 21.29554669
 19.86012857 20.02480328 21.19854962 18.91052046 19.79946305 20.16587486
 15.24036623 17.62554884 16.24441157 19.82577837 21.36632302 18.52848931
 19.65425152 16.82067934 18.81534563 20.76312523 24.70679323 26.17680132
 17.71571146 20.84706509 19.68285587 17.39216584 20.85532906 19.22540394
 18.42427779 18.77543693 19.75391977 26.04958067 29.82538634 27.7461615
 22.45651299 22.82617229 21.57637181 17.86689491 18.78224174 21.21771802
 15.7523132  17.64542212 21.17812468 22.51593928 26.00129836 21.48617409
 20.7648873  33.41670435 26.03470634 29.42393915 23.26887906 20.91861579
 19.42498135 21.20638654 25.71803969 28.7805479  32.39778062 23.95685233
 19.52974218 20.27518634 17.77558538 20.33679623 24.4272984  20.4138546
 21.32920143 22.91345556 22.65354578 22.890714   22.60892674 21.40425339
 22.66548379 19.26453233 27.21117

## · model: regressió polinòmica

In [37]:
# step_1: importar paquets i classes 

from sklearn.preprocessing import PolynomialFeatures

In [45]:
# step_2: obtenir variables que volem estudiar

# y: variable dependent (MEDV) 
# x: variable independent (RM)

rp_x = pv[
    ["RM"]
]
rp_y = pv["MEDV"]
rp_x,rp_y = np.array(rp_x), np.array(rp_y)

# per implementar regressió polinòmica s'han de transformar les dades d'entrada
# step_2b: transformar matriu d'entrada x -> que contingui columnes adicionals amb valors 𝑥²

# creació nova columna x

nova_x = PolynomialFeatures(degree=2, include_bias=False).fit_transform(rp_x)

In [46]:
nova_x

array([[ 6.575   , 43.230625],
       [ 6.421   , 41.229241],
       [ 7.185   , 51.624225],
       ...,
       [ 6.976   , 48.664576],
       [ 6.794   , 46.158436],
       [ 6.03    , 36.3609  ]])

In [47]:
# step_3: crear i ajustar model

model_rp = LinearRegression().fit(nova_x, rp_y)

# model de regressió polinòmica creat, ajustat i llest per aplicar
# .fit() és la matriu d'entrada modificada, la nova_x (no la rp_x original)

In [48]:
# step_4: obtenir resultats

rr_sq = model_rp.score(nova_x, rp_y)
print(f"coeficient de determinació: {rr_sq}")

print(f"intercepte: {model_rp.intercept_}")

print(f"coeficient: {model_rp.coef_}")

coeficient de determinació: 0.5484256373971057
intercepte: 66.05884748479394
coeficient: [-22.64326237   2.47012384]


In [49]:
# step_5: predir resposta

y_pred = model_rp.predict(nova_x)
print(f"predir resposta:\n{y_pred}")

predir resposta:
[23.96439498 22.50779105 30.88523643 28.56821216 30.40041143 22.58969374
 19.20806601 20.40050225 16.87772159 19.15176404 22.11313821 19.18691572
 18.37736318 18.77324701 19.81832577 18.03009321 18.67928335 19.0539964
 16.04769647 17.3973124  16.57122131 18.88181969 20.16728697 17.90144154
 18.60613405 16.71464228 17.90144154 19.45810464 23.19309448 24.96265241
 17.31870304 19.64040886 18.77999575 17.25209426 19.81832577 18.66593902
 18.07346125 18.12957585 18.88864748 24.16216035 28.88002533 25.97690034
 20.37698065 20.71032922 19.61836932 17.14808527 17.73923353 19.33590145
 15.81001035 16.72971607 18.86817895 19.96119474 23.34482517 19.10974506
 18.3709158  31.71790876 22.16639132 26.47902899 20.19040842 18.62602458
 17.47689005 18.88864748 22.82854933 25.89064071 29.86039711 21.36095393
 17.74517701 18.30671365 16.68961811 18.35160328 22.4715183  18.85455796
 19.58905244 20.98656563 21.21834257 21.32726987 21.26851296 20.15189738
 20.88027148 18.28117112 25.5169723

# EXERCICI 2
## comparació en base a MSE i R2 

In [55]:
# R2 - coeficient de determinació: mesura relativa de com s'ajusta el model a les variables dependents

import statsmodels.api as sm

In [53]:
# R_Square i Adjusted R_Square_Ajustat

# MODEL REGRESSIÓ LINEAL MÚLTIPLE

X_x = sm.add_constant(x)
result = sm.OLS(y, X_x).fit()
print(result.rsquared, result.rsquared_adj)

# resultat 0.4955246476058477 0.4935187813935449
# a partir del modelo de mostra -> gairebé 50% de la variabilitat dependent es pot explicar pel model
# R quadrada ajustada = (aprox) a R quadrada -> model bo per les variables


0.4955246476058477 0.4935187813935449


In [54]:
# R_Square i Adjusted R_Square_Ajustat

# MODEL REGRESSIÓ POLINÒMICA

X_nova_x = sm.add_constant(nova_x)
result = sm.OLS(rp_y, X_nova_x).fit()
print(result.rsquared, result.rsquared_adj)

# resultat 0.5484256373971057 0.5466301130925216
# a partir del modelo de mostra -> gairebé 55% de la variabilitat dependent es pot explicar pel model
# R quadrada ajustada = (aprox) a R quadrada -> model bastant robust

0.5484256373971057 0.5466301130925216


In [57]:
# MSE - error quadràtic mig -> mesura absoluta de l'ajust   
 
# paquets pel càlcul MSE

from sklearn.metrics import mean_squared_error
import math

In [70]:
# MSE -> MODEL REGRESSIÓ LINEAL MÚLTIPLE

y_true = y
y_predi = pred
mean_squared_error(y_true, y_predi)

42.58758534083955

In [71]:
# MSE -> MODEL REGRESSIÓ POLINÒMICA

yy_true = rp_y
yy_pred = y_pred
mean_squared_error(yy_true, yy_pred)

42.58758534083955

In [72]:
# R_Square i Adjusted R_Square_Ajustat -> Regressió Polinomiuca, valors mes elevatsi semblants, per tant model robust.
# MSE -> tots dos models de regressió són igual de bons. 

# EXERCICI 3
## entrenar els models amb els diferents paràmetres i intentar millorar la predicció

In [75]:
# numpy per convertir en matrius, fet en el primer pas (exercici 1)
# targets, labels -> valors que es volen predir
# features -> característiques, columnes que el model utilitza per fer una predicció = x
# label = y

# skicit-learn to split data into training and testing sets

from sklearn.model_selection import train_test_split

# split the data into training and testing sets
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size = 0.25, random_state = 42)

# valors per train/test

print('Training x Shape:', train_x.shape)
print('Training y Shape:', train_y.shape)
print('Testing x Shape:', test_x.shape)
print('Testing y Shape:', test_y.shape)


Training x Shape: (379, 2)
Training y Shape: (379,)
Testing x Shape: (127, 2)
Testing y Shape: (127,)


In [ ]:
# predicció line base -> son les mitges històriques
lineabase_pred = test_x[:, x_list.index('MEDS')]

# error linea base -> mostra l'error mig de la linea base
lineabase_error = abs(lineabase_pred - test_y)

print('mitja error linea base: ', round(np.mean(lineabase_error), 2))

In [105]:
# entrenar el model
# importacio del model utilitzat

from sklearn.ensemble import RandomForestRegressor

# 10 decisiontrees

rf = RandomForestRegressor(n_estimators = 10, random_state = 42)

# entrenamnet del model en l'entrenament de les dades

rf.fit(train_x, train_y)

RandomForestRegressor(n_estimators=10, random_state=42)

In [106]:
# utilitzar mètode predicció arbre en el test data

predictions = rf.predict(test_x)

# calcul error absolute

error = abs(predictions - test_y)

# imprimir error mig absolut (mae)
print('Mean Absolute Error:', round(np.mean(error), 2), 'degrees.')


Mean Absolute Error: 3.43 degrees.


# EXERCICI 4
## comparació del rendiment emprant l’aproximació traint/test o emprant totes les dades (validació interna)

# EXERCICI 5
## no utilitzar la variable "nombre habitacions (RM)" per fer prediccions.


In [107]:
# step_2: obtenir variables que volem estudiar

# y: variable dependent (MEDV) 
# x: variable independent (RM)

rpp_x = pv[
    ["LSTAT"]
]
rp_y = pv["MEDV"]
rpp_x,rp_y = np.array(rpp_x), np.array(rp_y)

# per implementar regressió polinòmica s'han de transformar les dades d'entrada
# step_2b: transformar matriu d'entrada x -> que contingui columnes adicionals amb valors 𝑥²

# creació nova columna x

altre_x = PolynomialFeatures(degree=2, include_bias=False).fit_transform(rpp_x)

altre_x

array([[ 4.98  , 24.8004],
       [ 9.14  , 83.5396],
       [ 4.03  , 16.2409],
       ...,
       [ 5.64  , 31.8096],
       [ 6.48  , 41.9904],
       [ 7.88  , 62.0944]])

In [109]:
# creació i ajust model

model_rpp = LinearRegression().fit(altre_x, rp_y)

# resultats

rrr_sq = model_rpp.score(altre_x, rp_y)

print(f"coeficient de determinació: {rrr_sq}")

print(f"intercepte: {model_rpp.intercept_}")

print(f"coeficient: {model_rpp.coef_}")



coeficient de determinació: 0.6407168971636612
intercepte: 42.862007328169355
coeficient: [-2.3328211   0.04354689]


In [110]:
# predir resposta

y_pred = model_rpp.predict(altre_x)
print(f"predir resposta:\n{y_pred}")

predir resposta:
[32.32453853 25.17791221 34.16797898 36.37991519 31.6651901  31.89005053
 20.59324886 14.15810743 12.05018872 15.70431246 13.36723387 19.57376939
 16.96093871 26.5640048  23.51133939 26.22710566 29.39746804 18.01119997
 21.54227676 22.08862187 13.06688286 18.92825716 14.4520986  13.69588164
 16.40699646 16.21714645 17.86433174 15.55389024 20.13661962 21.16467755
 12.38225972 19.84680295 11.65675676 14.71795763 13.42845365 24.36074714
 21.91380538 25.75248384 23.69917639 33.59690965 38.41374278 32.59126522
 30.7782899  27.91629545 24.55515102 23.5834102  18.57165584 14.39618326
 12.32493965 16.49875118 19.36330471 24.73590715 31.75872953 26.29098081
 17.87476572 32.64864303 30.85143182 34.32680433 28.90815379 25.05524819
 19.71564686 18.25618934 29.13448624 24.63031366 26.90474478 32.91744255
 23.54014159 26.82326784 19.7870559  25.72112109 29.1519574  24.06453835
 31.311726   27.74824658 29.04726111 25.48701088 21.17757628 23.49695136
 20.70612368 25.23945324 31.740004