# EXERCICI 1
## creació de dos models de classificació diferents per intentar predir millor les classes de l'arxiu.

In [1]:
# step_1: import packages and classes pel dataset

import numpy as np
import pandas as pd

# descarrega del dataset
bv = pd.read_csv('bon_vi.csv')
bv.head()

class  Alcohol  Malic aci    As  Alcalinity of ash  Magnesium  \
0      1    14.23       1.71  2.43               15.6        127   
1      1    13.20       1.78  2.14               11.2        100   
2      1    13.16       2.36  2.67               18.6        101   
3      1    14.37       1.95  2.50               16.8        113   
4      1    13.24       2.59  2.87               21.0        118   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0             5.64  1.04                          3.92     1065  
1             4.38  1.05                          3.40     1050  
2             5.68  1.03                          3.17     1185  
3             7.80  0.86                          3.45     1480  
4             4.32  1.04                          2.93      735

In [2]:
bv.shape

(178, 14)

In [3]:
bv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   class                         178 non-null    int64  
 1   Alcohol                       178 non-null    float64
 2   Malic aci                     178 non-null    float64
 3   As                            178 non-null    float64
 4   Alcalinity of ash             178 non-null    float64
 5   Magnesium                     178 non-null    int64  
 6   Total phenols                 178 non-null    float64
 7   Flavanoids                    178 non-null    float64
 8   Nonflavanoid phenols          178 non-null    float64
 9   Proanthocyanins               178 non-null    float64
 10  Color intensity               178 non-null    float64
 11  Hue                           178 non-null    float64
 12  OD280/OD315 of diluted wines  178 non-null    float64
 13  Proli

In [4]:
bv.describe()

class     Alcohol   Malic aci          As  Alcalinity of ash  \
count  178.000000  178.000000  178.000000  178.000000         178.000000   
mean     1.938202   13.000618    2.336348    2.366517          19.494944   
std      0.775035    0.811827    1.117146    0.274344           3.339564   
min      1.000000   11.030000    0.740000    1.360000          10.600000   
25%      1.000000   12.362500    1.602500    2.210000          17.200000   
50%      2.000000   13.050000    1.865000    2.360000          19.500000   
75%      3.000000   13.677500    3.082500    2.557500          21.500000   
max      3.000000   14.830000    5.800000    3.230000          30.000000   

        Magnesium  Total phenols  Flavanoids  Nonflavanoid phenols  \
count  178.000000     178.000000  178.000000            178.000000   
mean    99.741573       2.295112    2.029270              0.361854   
std     14.282484       0.625851    0.998859              0.124453   
min     70.000000       0.980000    0.340000              0.130000   
25%     88.000000       1.742500    1.205000              0.270000   
50%     98.000000       2.355000    2.135000              0.340000   
75%    107.000000       2.800000    2.875000              0.437500   
max    162.000000       3.880000    5.080000              0.660000   

       Proanthocyanins  Color intensity         Hue  \
count       178.000000       178.000000  178.000000   
mean          1.590899         5.058090    0.957449   
std           0.572359         2.318286    0.228572   
min           0.410000         1.280000    0.480000   
25%           1.250000         3.220000    0.782500   
50%           1.555000         4.690000    0.965000   
75%           1.950000         6.200000    1.120000   
max           3.580000        13.000000    1.710000   

       OD280/OD315 of diluted wines      Proline  
count                    178.000000   178.000000  
mean                       2.611685   746.893258  
std                        0.709990   314.907474  
min                        1.270000   278.000000  
25%                        1.937500   500.500000  
50%                        2.780000   673.500000  
75%                        3.170000   985.000000  
max                        4.000000  1680.000000

## · model arbres de classificació

In [5]:
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

In [6]:
# selecció de característiques del dataset
# divisió dataset característiques-variable objectiu

caract = ['Alcohol', 'As', 'Magnesium', 'Color intensity']
X = bv[caract] # característiques
y = bv['class'] # variable objectiu

In [7]:
# divisió dataset entrenament-test
# 80% entrenament - 20% test

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1) 

In [8]:
# creació objecte classificador de l'arbre de decisió

clf = DecisionTreeClassifier()

# entrenament classificador d'arbre de decisió

clf = clf.fit(X_train,y_train)

# predicció resposta conjunt dades prova

y_pred = clf.predict(X_test)


In [9]:
# precisió del model (vegades que el classificacor és correcte)

print("accuracy:",metrics.accuracy_score(y_test, y_pred))

accuracy: 0.8055555555555556


In [10]:
! pip install graphviz

In [11]:
! pip install pydotplus

from sklearn.tree import export_graphviz
from sklearn.externals.six import StringIO  
from IPython.display import Image  
import pydotplus

dot_data = StringIO()
export_graphviz(clf, out_file=dot_data,  
                filled=True, rounded=True,
                special_characters=True,feature_names = feature_cols,class_names=['0','1'])
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
graph.write_png('bon_vi.png')
Image(graph.create_png())


### No module named 'sklearn.externals.six' / no és possible veure l'arbre de classificació

## · model K-nearest Neighbors (KNN)

In [13]:
# creació de categories (3, segons dataframe) i assignació a una columna (As) 

bv["bv-cat"] = pd.qcut(bv["As"], 3, retbins=False, labels=[1, 2, 3])

In [14]:
# divisió conjunt dades en els seus atributs i etiquetes:

yk = bv['bv-cat']
Xk = bv.drop(['As', 'bv-cat'], axis = 1)

In [15]:
# divisio del dataset en train/test

Xk_train, Xk_test, yk_train, yk_test = train_test_split(Xk, yk, test_size=0.20, random_state=1)

In [16]:
# escalat de característiques per la classificació

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(Xk_train)

Xk_train = scaler.transform(Xk_train)
Xk_test = scaler.transform(Xk_test)

In [17]:
# entrenament i predicció per la classificació (aplicar classificació a les dades)
# aplicació del kNN_classifier (utilitza 5 veins)

from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier()
classifier.fit(Xk_train, yk_train)

KNeighborsClassifier()

In [18]:
# ajustat el KNeighborsClassifier -> es pot predir les classes de dades de prova

y_pred_k = classifier.predict(Xk_test)


# evaluació de les prediccions -> per classificació amb accurancy

acc =  classifier.score(Xk_test, yk_test)
print(acc) 

0.5277777777777778


## · model SVM (support vector machine)

In [19]:
from sklearn import svm

# creació classifacador SVM

#kernel lineal

clf_s = svm.SVC(kernel='linear') # Linear Kernel

# entrenament del model amb training sets

clf_s.fit(X_train, y_train)

# predicció pel dataset

y_pred_s = clf_s.predict(X_test)

In [20]:
# Model Accuracy: how often is the classifier correct?

print("accuracy_svm:",metrics.accuracy_score(y_test, y_pred_s))

accuracy_svm: 0.9166666666666666


# EXERCICI 2
## comparació dels models de classificació utilitzant la precisió (accuracy), una matriu de confusió i d’altres mètriques més avançades.

## · accuracy -> millor model SVM

In [29]:
# calculate accuracy - arbre classificació 

print("accuracy - arbre classificacio:",metrics.accuracy_score(y_test, y_pred))

accuracy - arbre classificacio: 0.8055555555555556


In [32]:
# calculate accuracy - knn 

acc =  classifier.score(Xk_test, yk_test)
print("accuracy - knn:", (acc))

accuracy - knn: 0.5277777777777778


In [31]:
# calculate accuracy - svm
      
print("accuracy_svm:",metrics.accuracy_score(y_test, y_pred_s))

accuracy_svm: 0.9166666666666666


In [33]:
# calcul null accuracy (for multi-class classification problems)
y_test.value_counts().head(1) / len(y_test)

1    0.388889
Name: class, dtype: float64

##  · matriu de confusió

In [52]:
# matriu de confusió -> descriu rendiment model classificació

# print the first 25 true and predicted responses
print('True', y_test.values[0:25])
print('Pred', y_pred[0:25])

True [3 2 1 2 1 3 2 1 3 2 1 1 2 1 2 2 3 1 2 1 1 2 3 2 1]
Pred [1 2 1 2 1 2 3 1 3 2 1 1 2 1 2 2 1 3 2 3 1 2 1 2 1]


In [54]:
# save confusion matrix and slice into four pieces
confusion = metrics.confusion_matrix(y_test, y_pred)
print(confusion)
#[row, column]
TP = confusion[1, 1]
TN = confusion[0, 0]
FP = confusion[0, 1]
FN = confusion[1, 0]

[[12  0  2]
 [ 0 12  1]
 [ 3  1  5]]


In [55]:
print((TP + TN) / float(TP + TN + FP + FN))
print(metrics.accuracy_score(y_test, y_pred))

1.0
0.8055555555555556


In [56]:
classification_error = (FP + FN) / float(TP + TN + FP + FN)
print(classification_error)
print(1 - metrics.accuracy_score(y_test, y_pred))

0.0
0.19444444444444442


In [59]:
sensitivity = TP / float(FN + TP)
print(sensitivity)

1.0


In [60]:
specificity = TN / (TN + FP)
print(specificity)

1.0


In [61]:
false_positive_rate = FP / float(TN + FP)
print(false_positive_rate)
print(1 - specificity)

0.0
0.0


In [63]:
precision = TP / float(TP + FP)
print(precision)

1.0


# EXERCICI 3
## entrenament amb els diferents paràmetres per millorar la predicció

In [72]:
# numpy per convertir en matrius, fet en el primer pas (exercici 1)
# targets, labels -> valors que es volen predir
# features -> característiques, columnes que el model utilitza per fer una predicció = x
# label = y

# skicit-learn to split data into training and testing sets

from sklearn.model_selection import train_test_split

# split the data into training and testing sets
train_x, test_x, train_y, test_y = train_test_split(X, y, test_size = 0.25, random_state = 178)

# valors per train/test

print('Training x Shape:', train_x.shape)
print('Training y Shape:', train_y.shape)
print('Testing x Shape:', test_x.shape)
print('Testing y Shape:', test_y.shape)

Training x Shape: (133, 4)
Training y Shape: (133,)
Testing x Shape: (45, 4)
Testing y Shape: (45,)


# EXERCICI 4
## comparació del rendiment amb aproximació traint/test o cross-validation

In [85]:
# estimació precisió

from sklearn.model_selection import cross_val_score

clf_cv= svm.SVC(kernel='linear', C=1, random_state=0)
scores = cross_val_score(clf_cv, X, y, cv=10)
scores

array([0.72222222, 0.66666667, 0.83333333, 0.72222222, 0.94444444,
       1.        , 0.83333333, 0.94444444, 0.82352941, 0.94117647])

In [86]:
print("%0.2f precisi' amb desviació standard %0.2f" % (scores.mean(), scores.std()))

0.84 precisi' amb desviació standard 0.11


In [87]:
from sklearn import metrics
scores = cross_val_score(
    clf_s, X, y, cv=10, scoring='f1_macro')
scores

array([0.71282051, 0.6540404 , 0.82435897, 0.70793651, 0.93732194,
       1.        , 0.81752137, 0.93732194, 0.81678322, 0.92592593])

In [89]:
from sklearn.model_selection import ShuffleSplit
n_samples = X.shape[0]
cv = ShuffleSplit(n_splits=10, test_size=0.3, random_state=0)
cross_val_score(clf_s, X, y, cv=cv)

array([0.88888889, 0.87037037, 0.83333333, 0.85185185, 0.83333333,
       0.87037037, 0.85185185, 0.83333333, 0.87037037, 0.87037037])

In [92]:
X = np.arange(10)
ss = ShuffleSplit(n_splits=10, test_size=0.25, random_state=0)
for train_index, test_index in ss.split(X):
    print("%s %s" % (train_index, test_index))

[9 1 6 7 3 0 5] [2 8 4]
[2 9 8 0 6 7 4] [3 5 1]
[4 5 1 0 6 9 7] [2 3 8]
[2 7 5 8 0 3 4] [6 1 9]
[4 1 0 6 8 9 3] [5 2 7]
[5 2 6 3 7 4 0] [1 8 9]
[7 8 6 5 4 9 0] [3 2 1]
[3 5 6 7 1 8 4] [0 9 2]
[1 4 5 3 6 0 2] [7 8 9]
[0 8 3 7 9 6 4] [1 2 5]


In [93]:
from sklearn.model_selection import KFold

X = ["a", "b", "c", "d"]
kf = KFold(n_splits=2)
for train, test in kf.split(X):
    print("%s %s" % (train, test))

[2 3] [0 1]
[0 1] [2 3]


In [96]:
# repetició kfold n vegades

from sklearn.model_selection import RepeatedKFold

X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
random_state = 12883823
rkf = RepeatedKFold(n_splits=2, n_repeats=5, random_state=random_state)
for train, test in rkf.split(X):
    print("%s %s" % (train, test))

[2 3] [0 1]
[0 1] [2 3]
[0 2] [1 3]
[1 3] [0 2]
[0 3] [1 2]
[1 2] [0 3]
[1 2] [0 3]
[0 3] [1 2]
[0 3] [1 2]
[1 2] [0 3]


# EXERCICI 5
## aplicació de processos d'enginyeria per millorar els resultats (normalització, estandarització, mostreig...)

In [100]:
#definico columnes
bv_x = bv[['Alcohol', 'As', 'Magnesium', 'Color intensity']]

#standarització valors per cada variable predictora
bv[['Alcohol', 'As', 'Magnesium', 'Color intensity']] = (bv_x-bv_x.mean())/bv_x.std()
bv_x

Alcohol        As  Magnesium  Color intensity
0    1.514341  0.231400   1.908522         0.251009
1    0.245597 -0.825667   0.018094        -0.292496
2    0.196325  1.106214   0.088110         0.268263
3    1.686791  0.486554   0.928300         1.182732
4    0.294868  1.835226   1.278379        -0.318377
..        ...       ...        ...              ...
173  0.873810  0.304301  -0.331985         1.139596
174  0.491955  0.413653   0.158126         0.967055
175  0.331822 -0.388260   1.418411         2.217979
176  0.208643  0.012696   1.418411         1.829761
177  1.391162  1.361368  -0.261969         1.786626

[178 rows x 4 columns]

In [104]:
#view mean of each predictor variable column
bv[['Alcohol', 'As', 'Magnesium', 'Color intensity']].mean()




Alcohol            1.297339e-16
As                 1.122697e-17
Magnesium          1.010428e-16
Color intensity    1.546828e-16
dtype: float64

In [105]:

#view standard deviation of each predictor variable column
bv[['Alcohol', 'As', 'Magnesium', 'Color intensity']].std()


Alcohol            1.0
As                 1.0
Magnesium          1.0
Color intensity    1.0
dtype: float64

In [108]:
caract_2 = ['Alcohol', 'As', 'Magnesium', 'Color intensity']
X3 = bv_x[caract_2] # característiques
y3 = bv['class'] # variable objectiu

In [109]:
# divisió dataset entrenament-test
# 80% entrenament - 20% test

X3_train, X3_test, y3_train, y3_test = train_test_split(X3, y3, test_size=0.2, random_state=1) 

In [110]:
# creació objecte classificador de l'arbre de decisió (3)

clf3 = DecisionTreeClassifier()

# entrenament classificador d'arbre de decisió

clf3 = clf3.fit(X3_train,y3_train)

# predicció resposta conjunt dades prova

y3_pred = clf3.predict(X3_test)


In [111]:
# precisió del model (vegades que el classificacor és correcte)

print("accuracy:",metrics.accuracy_score(y3_test, y3_pred))

accuracy: 0.7777777777777778
